[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_escrow = "DcUJPJZDTW9pSFmfpxoQkedaAv3UCdbhDLEHHiK2rZBx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
script = "vitest run"
